objects = application.o black_bird.o bluejay.o character.o clam.o egg.o fly.o level.o main.o \
          mosquito.o platform.o rectangle.o ghost.o master_ecto.o rock.o goldenjay.o swooper.o \
          switch.o super_mosquito.o lemming.o throwable_rock.o stop_attack_object.o \
          tomatoo_plant.o scrolling_background_object.o string_list.o message_object.o \
          spiked_pole.o boiling_mud.o mud_drop.o

bluejay : $(objects)
	g++ -o ..\bluejay $(objects) -lalleg

application.o :
black_bird.o :
bluejay.o :
character.o :
clam.o :
egg.o :
fly.o :
level.o :
main.o :
mosquito.o :
platform.o :
rectangle.o :
ghost.o :
master_ecto.o :
rock.o :
goldenjay.o :
swooper.o :
switch.o :
super_mosquito.o :
lemming.o :
throwable_rock.o :
stop_attack_object.o :
tomatoo_plant.o :
scrolling_background_object.o :
string_list.o :
message_object.o :
spiked_pole.o :
boiling_mud.o :
mud_drop.o :

clean :
	del *.o
